export type ErrorCode =
  | "INVALID_INPUT"
  | "SCENE_NOT_FOUND"
  | "SCENE_EXPIRED"
  | "SCENE_VERSION_CONFLICT"
  | "SCENE_VERSION_UNSUPPORTED"
  | "BUILDING_UID_NOT_IN_SCENE"
  | "EXPORT_LIMIT_EXCEEDED"
  | "EXPORT_GLTF_FAILED"
  | "PLATEAU_CORE_ERROR"
  | "UPSTREAM_PLATEAU_ERROR"
  | "OSM_OVERPASS_ERROR"
  | "RATE_LIMITED"
  | "PATH_SECURITY_ERROR"
  | "INTERNAL_ERROR";

export const RETRYABLE_CODES: ReadonlySet<ErrorCode> = new Set([
  "PLATEAU_CORE_ERROR",
  "UPSTREAM_PLATEAU_ERROR",
  "OSM_OVERPASS_ERROR",
  "RATE_LIMITED",
]);
